add_newline = false
command_timeout = 1000

[aws]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
format = "[$path]($style) "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[git_branch]
style = "bold yellow"
format = " [$symbol $branch]($style) "
symbol = "ğŸŒ±"

[hostname]
ssh_only = false
format = "[$hostname](bold gray)[: ](bold  white)"
style = "bold blue"

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

[sudo]
style = "bold green"
disabled = false

[username]
disabled = true
